### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by SaraWolk** [drinkablebreeze/starbestfit.com#3]
### Proposed feature or solution

Hi, this is Sara Wolk, Executive Director over at the STAR Voting project. I just got an email sharing your site and gave it a try. The site is fantastic, well made and I have no feedback. Bravo! 

Thank you for making STAR Voting look good, creating a tool that we've wanted but didn't have time to create yet, and using our current best practices to present it correctly and link to our site! Please drop us a line anytime at info@equal.vote

**Comment by SaraWolk** [comment]
Hi DrinkableBreeze,
By editing the poll I meant having the feature where the creator of the
poll would be able to create it, then go back and make changes if they did
something wrong or realized that a date needed to be added or removed. For
example when I created my test, I put the days in on the wrong week, so I
had Thursday and Friday the 18th and 19th instead of the 11th and 12th. I
could always just recreate it, but I'd already sent out the link so a quick
edit would be awesome. I would also use an "add to google calendar option"
a lot if it was available, and if it automatically added the people who'd
been invited to the poll that would be a game changer.

Obviously there are a whole list of features that would be great to have,
ideally, and I'm sure you have a laundry list of your own, but again, as
is, the site is absolutely fantastic and it already is WAY better than
doodle or whentomeet and other tools we all use regularly. We'll definitely
be sharing it and singing its praises from the rooftop!

If you'd like to get involved with our team we have a Slack and a
#softwaredev channel where our team is working on a new voting app/site
that will be a huge upgrade over star.vote, with tons of new features
available.
https://join.slack.com/t/starvoting/shared_invite/zt-29pvtzjua-UDyJNYRgPKdH6jENTJfCGQ

In solidarity,

**Comment by wolftune** [comment]
FWIW, the idea of poll-editing (and also *response* editing, attendees coming back and changing their responses if their availability changes) is indeed an important feature. It is something that WhenIsGood does have.

It relates to https://github.com/GRA0007/crab.fit/issues/137 and https://github.com/GRA0007/crab.fit/issues/134 which are rejected issues for the original crabfit software. Having user accounts  and access controls (who is allowed to see what) is *one* way to manage editing.

However, it's also feasible to do a method with a special URL for each of editing the poll and editing each response — that could be done without any privacy controls of user accounts. It would be a case where losing the special URL would mean no way to edit. So, it would just tell each person that they better note this URL if they want the chance to edit later. It could be sensible with that approach to let the poll-edit URL be the *master* edit that has access to the different special URLs for editing responses (which would let the master URL change people's responses or to send responders their appropriate URL in order to edit).

**Comment by altsalt** [comment]
I've gone through and duplicated (or teased apart and hopefully clarified) most of the crab.fit feature requests for future discussion/implementation here.

To that end, #4 and #8 are copies of those relevant issues. I've also created #5 which is a boiled down variant of this feature request.

**Comment by SaraWolk** [comment]
We demoed the site at our last Oregon state STAR Voting chapter meeting and
had fun with it. We did run into a number of people a bit confused that
there was no "submit" or "done" button.

**Comment by altsalt** [comment]
Ah yes, that was something that I was only familiar with due to when2meet, and have been fielding questions about this morning as I am trying to use this to schedule an upcoming meeting. Having a submit/save button that doesn't actually do anything unless #6 is implemented, might be valuable just for UX sake.

**Comment by SaraWolk** [comment]
Hi, I wanted to let you know there's an error happening with our STAR Best
Fit poll and they whole page isn't working.
https://starbestfit.com/meet-up-on-larry-taylor-resolution-566529

More info below.

Thanks again for the great app.


"Unfortunately the starbestfit page is giving me a series of React errors,
and not loading properly. I've put the error below."

5769-81026e38e074a23f.js:1 TypeError: Cannot read properties of undefined
(reading 'rankedWins')
    at T (8071-0d624e5f96c4227f.js:1:13683)
    at k (8071-0d624e5f96c4227f.js:1:12805)
    at f (8071-0d624e5f96c4227f.js:1:10790)
    at 4324-01976bb733b65f5c.js:1:2408
    at Object.rQ [as useMemo] (bce60fc1-0a1d643f38e6abf5.js:9:43862)
    at t.useMemo (5769-81026e38e074a23f.js:17:7340)
    at N (4324-01976bb733b65f5c.js:1:2395)
    at rf (bce60fc1-0a1d643f38e6abf5.js:9:39184)
    at rs (bce60fc1-0a1d643f38e6abf5.js:9:38895)
    at lg (bce60fc1-0a1d643f38e6abf5.js:9:54275)
window.console.error @ 5769-81026e38e074a23f.js:1
ln @ bce60fc1-0a1d643f38e6abf5.js:9
n.callback @ bce60fc1-0a1d643f38e6abf5.js:9
nf @ bce60fc1-0a1d643f38e6abf5.js:9
nd @ bce60fc1-0a1d643f38e6abf5.js:9
av @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
aD @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
aD @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
aD @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
aD @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
aD @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
aD @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
aD @ bce60fc1-0a1d643f38e6abf5.js:9
ak @ bce60fc1-0a1d643f38e6abf5.js:9
(anonymous) @ bce60fc1-0a1d643f38e6abf5.js:9
oU @ bce60fc1-0a1d643f38e6abf5.js:9
oE @ bce60fc1-0a1d643f38e6abf5.js:9
ok @ bce60fc1-0a1d643f38e6abf5.js:9
E @ 5769-81026e38e074a23f.js:25
C @ 5769-81026e38e074a23f.js:25
